import HomeIcon from 'components/icons/HomeIcon';
import { Users, BarChart, Briefcase, Settings, Power } from 'react-feather';

const adminRoutes = [
  // {
  //   id: 1,
  //   collapse: false,
  //   expand: 'down',
  //   path: '/dashboard',
  //   name: 'Dashboard',
  //   hasEmployee: false,
  //   permission: [],
  //   icon: HomeIcon,
  //   childs: [],
  // },
  {
    id: 2,
    collapse: false,
    expand: 'down',
    path: '/staffs',
    name: 'Staff',
    permission: [],
    icon: Users,
    childs: [],
  },
  {
    id: 3,
    collapse: true,
    expand: 'down',
    path: '/agents',
    name: 'FBA Agents',
    permission: [],
    icon: Users,
    childs: [
      {
        id: 1,
        collapse: false,
        path: '/agents',
        childPath: '/list',
        name: 'Agent List',
        type: 'admin',
        permission: [],
        icon: Users,
      },
      {
        id: 2,
        collapse: false,
        path: '/agents',
        childPath: '/add',
        name: 'Add Agents',
        type: 'admin',
        permission: [],
        icon: Users,
      },
    ],
  },
  {
    id: 4,
    collapse: true,
    expand: 'down',
    path: '/farmers',
    name: 'Farmers',
    permission: [],
    icon: Users,
    childs: [
      {
        id: 1,
        collapse: false,
        path: '/farmers',
        childPath: '/list',
        name: 'Farmer List',
        type: 'admin',
        permission: [],
        icon: Users,
      },
    ],
  },
  {
    id: 5,
    collapse: false,
    expand: 'down',
    path: '/reports',
    name: 'Reports',
    permission: [],
    icon: BarChart,
    childs: [],
  },
  {
    id: 6,
    collapse: false,
    expand: 'down',
    path: '/services',
    name: 'Service',
    permission: [],
    icon: Briefcase,
    childs: [],
  },
  {
    id: 7,
    collapse: false,
    expand: 'down',
    path: '/settings',
    name: 'Settings',
    permission: [],
    icon: Settings,
    childs: [],
  },
  {
    id: 8,
    collapse: false,
    expand: 'down',
    path: '/logout',
    name: 'Logout',
    permission: [],
    icon: Power,
    childs: [],
  },
];

export default adminRoutes;
